version: '2'

services:
  api:
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    image: api
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - ./src/Api:/app
    links:
      - rabbit
  service1:
    build:
      context: ./src/Service1
      dockerfile: Dockerfile
    image: service1
    container_name: service1
    volumes:
      - ./src/Service1:/app
    links:
      - rabbit
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 8080:15672
    hostname: my-rabbit
